import React, { useState } from 'react';
import type { AccessEvent, AuditEvent, BackupRun, ErrorEvent, PilotFeedback, PilotProgram, PrivacySettings, User } from '../types';
import { secureApi } from '../lib/secureApi';
import { useLanguage } from '../i18n';

export default function QualityCenter({ users, privacy, auditEvents, accessEvents, backups, errors, pilot, feedback, onChanged }: { users: User[]; privacy: PrivacySettings; auditEvents: AuditEvent[]; accessEvents: AccessEvent[]; backups: BackupRun[]; errors: ErrorEvent[]; pilot: PilotProgram | null; feedback: PilotFeedback[]; onChanged: () => Promise<void> }) {
  const { locale } = useLanguage(); const fr = locale === 'fr';
  const [form, setForm] = useState(privacy); const [selected, setSelected] = useState<string[]>([]); const [duration, setDuration] = useState(14); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState('');
  const run = async (name: string, task: () => Promise<unknown>) => { setBusy(name); setNotice(''); try { await task(); setNotice(fr ? 'Opération terminée.' : 'Actie voltooid.'); await onChanged(); } catch (error) { setNotice(error instanceof Error ? error.message : 'Fout'); } finally { setBusy(''); } };
  const field = (key: keyof PrivacySettings, label: string, type: 'text' | 'email' | 'number' = 'number') => <label className="text-sm font-bold">{label}<input type={type} value={String(form[key] ?? '')} onChange={event => setForm({ ...form, [key]: type === 'number' ? Number(event.target.value) : event.target.value })} className="mt-1 w-full border border-zinc-200 rounded-xl p-3 font-normal" /></label>;
  return <div className="space-y-6">
    <div><h2 className="text-2xl font-bold">{fr ? 'Confidentialité et qualité' : 'Privacy en kwaliteit'}</h2><p className="text-sm text-zinc-500">{fr ? 'Conservation, sauvegardes, surveillance et pilote.' : 'Bewaring, back-ups, monitoring en pilot.'}</p></div>
    {notice && <div role="status" className="p-3 rounded-xl bg-blue-50 border border-blue-200 text-sm font-semibold">{notice}</div>}
    <section className="bg-white border border-zinc-200 rounded-2xl p-6 space-y-4"><h3 className="font-bold text-lg">{fr ? 'Paramètres de confidentialité' : 'Privacy-instellingen'}</h3><div className="grid md:grid-cols-2 gap-3">{field('controllerName', fr ? 'Responsable du traitement' : 'Verwerkingsverantwoordelijke', 'text')}{field('contactEmail', 'Contact e-mail', 'email')}{field('locationDays', fr ? 'Localisation (jours)' : 'Locatie (dagen)')}{field('notificationDays', fr ? 'Notifications (jours)' : 'Meldingen (dagen)')}{field('auditDays', fr ? 'Journaux accès/modification (jours)' : 'Toegangs-/wijzigingslogs (dagen)')}{field('errorDays', fr ? 'Erreurs (jours)' : 'Foutlogs (dagen)')}{field('backupDays', fr ? 'Sauvegardes (jours)' : 'Back-ups (dagen)')}</div><div className="flex flex-wrap gap-2"><button disabled={!!busy} onClick={() => run('save', () => secureApi.updatePrivacySettings(form))} className="bg-zinc-900 text-white rounded-xl px-5 py-3 font-bold">{fr ? 'Enregistrer' : 'Opslaan'}</button><button disabled={!!busy} onClick={() => run('cleanup', () => secureApi.runPrivacyCleanup())} className="border border-zinc-300 rounded-xl px-5 py-3 font-bold">{fr ? 'Nettoyer maintenant' : 'Nu opschonen'}</button></div><p className="text-xs text-zinc-500">{fr ? 'Dernier nettoyage' : 'Laatste opschoning'}: {privacy.lastCleanupAt ? new Date(privacy.lastCleanupAt).toLocaleString(locale === 'fr' ? 'fr-BE' : 'nl-BE') : '—'}</p></section>
    <section className="bg-white border border-zinc-200 rounded-2xl p-6 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold text-lg">{fr ? 'Sauvegardes et test de restauration' : 'Back-ups en hersteltest'}</h3><p className="text-xs text-zinc-500">{fr ? 'Le test relit le fichier et vérifie checksum, JSON et tables.' : 'De test leest het bestand terug en controleert checksum, JSON en tabellen.'}</p></div><div className="flex gap-2"><button disabled={!!busy} onClick={() => run('backup', () => secureApi.createBackup())} className="border rounded-xl px-4 py-2 font-bold">{fr ? 'Créer' : 'Maken'}</button><button disabled={!!busy || !backups.length} onClick={() => run('test', () => secureApi.testLatestBackup())} className="bg-zinc-900 text-white rounded-xl px-4 py-2 font-bold">{fr ? 'Tester' : 'Testen'}</button></div></div>{backups.length ? <ul className="space-y-2 text-sm">{backups.slice(0, 5).map(item => <li key={item.id} className="border-t pt-2 flex justify-between gap-2"><span>{new Date(item.createdAt).toLocaleString()}</span><span className={item.testStatus === 'passed' ? 'text-green-700 font-bold' : 'text-zinc-500'}>{item.testStatus === 'passed' ? (fr ? 'test réussi' : 'test geslaagd') : (fr ? 'non testé' : 'niet getest')}</span></li>)}</ul> : <p className="text-sm text-zinc-500">{fr ? 'Aucune sauvegarde.' : 'Nog geen back-up.'}</p>}</section>
    <section className="grid md:grid-cols-2 gap-4"><div className="bg-white border rounded-2xl p-5"><h3 className="font-bold">{fr ? 'Surveillance des erreurs' : 'Foutmonitoring'} <span className="text-red-600">({errors.length})</span></h3><ul className="mt-3 space-y-2 text-xs max-h-64 overflow-auto">{errors.slice(0, 15).map(item => <li key={item.id} className="border-t pt-2"><strong>{item.action || 'request'}</strong> · {item.message}<br/><span className="text-zinc-400">{new Date(item.createdAt).toLocaleString()}</span></li>)}</ul></div><div className="bg-white border rounded-2xl p-5"><h3 className="font-bold">{fr ? 'Accès et modifications' : 'Toegang en wijzigingen'}</h3><p className="text-xs text-zinc-500 mt-1">{accessEvents.length} {fr ? 'accès récents' : 'recente toegangen'} · {auditEvents.length} {fr ? 'modifications' : 'wijzigingen'}</p><ul className="mt-3 space-y-2 text-xs max-h-64 overflow-auto">{auditEvents.slice(0, 15).map(item => <li key={item.id} className="border-t pt-2"><strong>{item.action}</strong> · {users.find(user => user.id === item.actorId)?.name || item.actorId}<br/><span className="text-zinc-400">{new Date(item.createdAt).toLocaleString()}</span></li>)}</ul></div></section>
    <section className="bg-white border border-zinc-200 rounded-2xl p-6 space-y-4"><h3 className="font-bold text-lg">Pilot</h3>{pilot ? <><p className="text-sm">{pilot.members.map(item => item.name).join(', ')} · {new Date(pilot.startedAt).toLocaleDateString()} – {new Date(pilot.endsAt).toLocaleDateString()}</p><button disabled={!!busy} onClick={() => run('close', () => secureApi.closePilot(pilot.id))} className="border border-red-300 text-red-700 rounded-xl px-4 py-2 font-bold">{fr ? 'Clôturer le pilote' : 'Pilot afsluiten'}</button><div className="space-y-2">{feedback.map(item => <article key={item.id} className="bg-zinc-50 rounded-xl p-3 text-sm"><strong>{users.find(user => user.id === item.userId)?.name || item.userId} · {item.rating}/5 · {item.category}</strong><p>{item.message}</p></article>)}</div></> : <><p className="text-sm text-zinc-500">{fr ? 'Sélectionnez 2 à 5 travailleurs actifs.' : 'Selecteer 2 tot 5 actieve werknemers.'}</p><div className="grid md:grid-cols-2 gap-2">{users.filter(item => item.active !== false).map(item => <label key={item.id} className="border rounded-xl p-3 text-sm flex gap-2"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])}/>{item.name}</label>)}</div><label className="text-sm font-bold">{fr ? 'Durée (jours)' : 'Duur (dagen)'}<input type="number" min="7" max="30" value={duration} onChange={e => setDuration(Number(e.target.value))} className="ml-2 border rounded-lg p-2" /></label><button disabled={!!busy || selected.length < 2 || selected.length > 5} onClick={() => run('pilot', () => secureApi.startPilot(selected, duration))} className="bg-zinc-900 text-white rounded-xl px-5 py-3 font-bold disabled:opacity-50">{fr ? 'Démarrer le pilote' : 'Pilot starten'}</button></>}</section>
  </div>;
}
